name: CI/CD Credit Simulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build dengan Maven
        run: mvn clean package

      - name: Jalankan Unit Test
        run: mvn test

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: credit-simulator
          path: target/credit-simulator-1.0-SNAPSHOT.jar
